// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/improbable/spatialos/playerauth/v1alpha1/player_identity.proto
// Original file comments:
// / Provides methods to manage player tokens.
//
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Improbable.SpatialOS.PlayerAuth.V1Alpha1 {
  /// <summary>
  //// PlayerAuthenticationService provides methods for generation of player authentication.
  /// </summary>
  public static partial class PlayerTokenService
  {
    static readonly string __ServiceName = "improbable.spatialos.playerauth.v1alpha1.PlayerTokenService";

    static readonly grpc::Marshaller<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest> __Marshaller_CreatePlayerTokenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse> __Marshaller_CreatePlayerTokenResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest, global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse> __Method_CreatePlayerToken = new grpc::Method<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest, global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreatePlayerToken",
        __Marshaller_CreatePlayerTokenRequest,
        __Marshaller_CreatePlayerTokenResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.PlayerIdentityReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PlayerTokenService</summary>
    public abstract partial class PlayerTokenServiceBase
    {
      /// <summary>
      //// Returns a new token required to access the requested project
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse> CreatePlayerToken(global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PlayerTokenService</summary>
    public partial class PlayerTokenServiceClient : grpc::ClientBase<PlayerTokenServiceClient>
    {
      /// <summary>Creates a new client for PlayerTokenService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PlayerTokenServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PlayerTokenService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PlayerTokenServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PlayerTokenServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PlayerTokenServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      //// Returns a new token required to access the requested project
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse CreatePlayerToken(global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreatePlayerToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// Returns a new token required to access the requested project
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse CreatePlayerToken(global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreatePlayerToken, null, options, request);
      }
      /// <summary>
      //// Returns a new token required to access the requested project
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse> CreatePlayerTokenAsync(global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreatePlayerTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// Returns a new token required to access the requested project
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenResponse> CreatePlayerTokenAsync(global::Improbable.SpatialOS.PlayerAuth.V1Alpha1.CreatePlayerTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreatePlayerToken, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PlayerTokenServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlayerTokenServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PlayerTokenServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreatePlayerToken, serviceImpl.CreatePlayerToken).Build();
    }

  }
}
#endregion
