#!/usr/bin/env bash
# See https://brevi.link/shell-style and https://explainshell.com
## This is a bazel script to ensure that the currently executed version of bazel is the REQUIRED version in the WORKSPACE file.
##
## Usage:
##  This is used by bazel when any bazel command is called.
##  It is the same as the copy in the everything repo.
##

set -e -u -o pipefail

TOOLS_DIR="$(dirname "$0")"

source "${TOOLS_DIR}"/../scripts/includes/os.sh

# All information required for the script to select or, if necessary, install bazel is contained
# in this code block.
# If a higher version of bazel is required, update `REQUIRED_BAZEL_VERSION` and the
# `REQUIRED_BAZEL_SHA256` values for each platform.
REQUIRED_BAZEL_VERSION="1.2.1"
BAZEL_INSTALLATION_DIR="${HOME}/.bazel_installations/${REQUIRED_BAZEL_VERSION}"
DOWNLOAD_CMD="curl -L -s -o bazel"
if isLinux; then
  REQUIRED_BAZEL_SHA256="f5e21d7448419d1596ad0c5bb71fb336a0af08c832587aec394970ea56701d88"
  REQUIRED_BAZEL_SHA256CMD="sha256sum"
  BAZEL_EXE="bazel-${REQUIRED_BAZEL_VERSION}-linux-x86_64"
elif isMacOS; then
  REQUIRED_BAZEL_SHA256="6729be5a56e6eadf7a9112afd2d87ce348da8fca22077b882d9bb7a6f5d41d1c"
  REQUIRED_BAZEL_SHA256CMD="shasum -a 256"
  BAZEL_EXE="bazel-${REQUIRED_BAZEL_VERSION}-darwin-x86_64"
else
  REQUIRED_BAZEL_SHA256="5b1a1077015090aec75c20b49c5f77ac9707b86f8e0b55c00e96e315f00f47cf"
  REQUIRED_BAZEL_SHA256CMD="sha256sum"
  # Windows does not have an installer but retrieves the executable directly.
  BAZEL_EXE="bazel-${REQUIRED_BAZEL_VERSION}-windows-x86_64.exe"
fi

BAZEL_TARGET_PATH="${BAZEL_INSTALLATION_DIR}/bin/bazel"

# Check if correct version is already installed.
if [ -x "${BAZEL_TARGET_PATH}" ]; then
  exec -a "$0" "${BAZEL_TARGET_PATH}" "$@"
fi

cat <<EOM
=================================================
Bazel version ${REQUIRED_BAZEL_VERSION} is not
installed under ~/.bazel_installations

Installing bazel ${REQUIRED_BAZEL_VERSION} now...
=================================================
EOM

# Create root directory if needed.
if [ ! -d "${BAZEL_INSTALLATION_DIR}" ]; then
  echo "Installation directory created."
  mkdir -p "${BAZEL_INSTALLATION_DIR}"
fi

function _are_checksums_equal() {
  CHECKSUM_A=$1
  CHECKSUM_B=$2
  # Split apart the checksum from the file name by splitting the returned string by the contained
  # space; the checksum has the format:
  # xxxxxx...xxxxx <filename>
  CHECKSUM_A_PARTS=(${CHECKSUM_A})
  CHECKSUM_B_PARTS=(${CHECKSUM_B})

  if [[ "${CHECKSUM_A_PARTS[0]}" == "${CHECKSUM_B_PARTS[0]}" ]]; then
    return 0 # True
  else
    return 1 # False
  fi
}

# Install correct bazel version.
# If we don't have a local Bazel install at this point we need to retrieve the right version from GitHub.
mkdir -p "${BAZEL_INSTALLATION_DIR}/bin"
pushd "${BAZEL_INSTALLATION_DIR}/bin"
echo "Starting download of bazel ${REQUIRED_BAZEL_VERSION}..."
${DOWNLOAD_CMD} "https://github.com/bazelbuild/bazel/releases/download/${REQUIRED_BAZEL_VERSION}/${BAZEL_EXE}"
echo "Download finished."
echo "Testing download file integrity..."
CALCULATED_CHECKSUM="$(${REQUIRED_BAZEL_SHA256CMD} bazel)"
if ! _are_checksums_equal "${CALCULATED_CHECKSUM}" "${REQUIRED_BAZEL_SHA256}"; then
  cat <<EOM
  ABORT - Downloaded Bazel failed the SHA-256 hash check.
  ABORT - Expected: ${REQUIRED_BAZEL_SHA256}  bazel
  ABORT - Found:    ${CALCULATED_CHECKSUM}
EOM
  exit 1
fi

if [ -f "${BAZEL_TARGET_PATH}" ]; then
  chmod a+x "${BAZEL_TARGET_PATH}"

  if [ ! -x "${BAZEL_TARGET_PATH}" ]; then
    echo "Couldn't mark bazel binary as executable."
    echo "$(ls -l ${BAZEL_TARGET_PATH})"
    exit 1
  fi
else
  echo "Couldn't install bazel properly - executable doesn't exist."
  echo "$(ls -l ${BAZEL_TARGET_PATH})"
  exit 1
fi
popd

echo "Executing downloaded bazel..."
exec -a "$0" "${BAZEL_TARGET_PATH}" "$@"
